import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/NAvbar";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/Context/Context";
import WishListContextProvider from "@/components/Context/WishListContext";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";
import Footer from "@/components/Footer/Footer";
import "animate.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-teal-50`}
      >
        
        <MySessionProvider>
          <CartContextProvider>
          <WishListContextProvider>
            <Toaster/>
          <Navbar/>
        <div className=" pt-20  pb-15">
        {children}
        </div>
        <Footer/>
          </WishListContextProvider>
        </CartContextProvider>
        </MySessionProvider>
        

      </body>
    </html>
  );
}
